# Generated by Django 3.0.4 on 2020-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.TextField(unique=True),
        ),
    ]
