# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hw_file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hw_file.proto',
  package='lms_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rhw_file.proto\x12\tlms_proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x19\n\tUserReply\x12\x0c\n\x04role\x18\x01 \x01(\t\"3\n\rCourseRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\"#\n\x0b\x43ourseReply\x12\x14\n\x0cvalid_course\x18\x01 \x01(\x08\"\x1b\n\tFileReply\x12\x0e\n\x06hw_url\x18\x01 \x01(\t\"\x1c\n\x0b\x46ileRequest\x12\r\n\x05hw_id\x18\x01 \x01(\t2\xd0\x01\n\x12HomeworkController\x12:\n\x08Userrole\x12\x16.lms_proto.UserRequest\x1a\x14.lms_proto.UserReply\"\x00\x12@\n\nValidation\x12\x18.lms_proto.CourseRequest\x1a\x16.lms_proto.CourseReply\"\x00\x12<\n\nHomeworkID\x12\x16.lms_proto.FileRequest\x1a\x14.lms_proto.FileReply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='lms_proto.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='lms_proto.UserRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=87,
)


_USERREPLY = _descriptor.Descriptor(
  name='UserReply',
  full_name='lms_proto.UserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='lms_proto.UserReply.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=114,
)


_COURSEREQUEST = _descriptor.Descriptor(
  name='CourseRequest',
  full_name='lms_proto.CourseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='lms_proto.CourseRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='course_id', full_name='lms_proto.CourseRequest.course_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=167,
)


_COURSEREPLY = _descriptor.Descriptor(
  name='CourseReply',
  full_name='lms_proto.CourseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid_course', full_name='lms_proto.CourseReply.valid_course', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=204,
)


_FILEREPLY = _descriptor.Descriptor(
  name='FileReply',
  full_name='lms_proto.FileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hw_url', full_name='lms_proto.FileReply.hw_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=233,
)


_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='lms_proto.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hw_id', full_name='lms_proto.FileRequest.hw_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserReply'] = _USERREPLY
DESCRIPTOR.message_types_by_name['CourseRequest'] = _COURSEREQUEST
DESCRIPTOR.message_types_by_name['CourseReply'] = _COURSEREPLY
DESCRIPTOR.message_types_by_name['FileReply'] = _FILEREPLY
DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'hw_file_pb2'
  # @@protoc_insertion_point(class_scope:lms_proto.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserReply = _reflection.GeneratedProtocolMessageType('UserReply', (_message.Message,), {
  'DESCRIPTOR' : _USERREPLY,
  '__module__' : 'hw_file_pb2'
  # @@protoc_insertion_point(class_scope:lms_proto.UserReply)
  })
_sym_db.RegisterMessage(UserReply)

CourseRequest = _reflection.GeneratedProtocolMessageType('CourseRequest', (_message.Message,), {
  'DESCRIPTOR' : _COURSEREQUEST,
  '__module__' : 'hw_file_pb2'
  # @@protoc_insertion_point(class_scope:lms_proto.CourseRequest)
  })
_sym_db.RegisterMessage(CourseRequest)

CourseReply = _reflection.GeneratedProtocolMessageType('CourseReply', (_message.Message,), {
  'DESCRIPTOR' : _COURSEREPLY,
  '__module__' : 'hw_file_pb2'
  # @@protoc_insertion_point(class_scope:lms_proto.CourseReply)
  })
_sym_db.RegisterMessage(CourseReply)

FileReply = _reflection.GeneratedProtocolMessageType('FileReply', (_message.Message,), {
  'DESCRIPTOR' : _FILEREPLY,
  '__module__' : 'hw_file_pb2'
  # @@protoc_insertion_point(class_scope:lms_proto.FileReply)
  })
_sym_db.RegisterMessage(FileReply)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'hw_file_pb2'
  # @@protoc_insertion_point(class_scope:lms_proto.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)



_HOMEWORKCONTROLLER = _descriptor.ServiceDescriptor(
  name='HomeworkController',
  full_name='lms_proto.HomeworkController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=266,
  serialized_end=474,
  methods=[
  _descriptor.MethodDescriptor(
    name='Userrole',
    full_name='lms_proto.HomeworkController.Userrole',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Validation',
    full_name='lms_proto.HomeworkController.Validation',
    index=1,
    containing_service=None,
    input_type=_COURSEREQUEST,
    output_type=_COURSEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HomeworkID',
    full_name='lms_proto.HomeworkController.HomeworkID',
    index=2,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOMEWORKCONTROLLER)

DESCRIPTOR.services_by_name['HomeworkController'] = _HOMEWORKCONTROLLER

# @@protoc_insertion_point(module_scope)
