# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import hw_file_pb2 as hw__file__pb2


class HomeworkControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validation = channel.unary_unary(
                '/lms_proto.HomeworkController/Validation',
                request_serializer=hw__file__pb2.CourseRequest.SerializeToString,
                response_deserializer=hw__file__pb2.CourseReply.FromString,
                )
        self.HomeworkID = channel.unary_unary(
                '/lms_proto.HomeworkController/HomeworkID',
                request_serializer=hw__file__pb2.FileRequest.SerializeToString,
                response_deserializer=hw__file__pb2.FileReply.FromString,
                )


class HomeworkControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Validation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HomeworkID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HomeworkControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validation': grpc.unary_unary_rpc_method_handler(
                    servicer.Validation,
                    request_deserializer=hw__file__pb2.CourseRequest.FromString,
                    response_serializer=hw__file__pb2.CourseReply.SerializeToString,
            ),
            'HomeworkID': grpc.unary_unary_rpc_method_handler(
                    servicer.HomeworkID,
                    request_deserializer=hw__file__pb2.FileRequest.FromString,
                    response_serializer=hw__file__pb2.FileReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lms_proto.HomeworkController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HomeworkController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Validation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lms_proto.HomeworkController/Validation',
            hw__file__pb2.CourseRequest.SerializeToString,
            hw__file__pb2.CourseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HomeworkID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lms_proto.HomeworkController/HomeworkID',
            hw__file__pb2.FileRequest.SerializeToString,
            hw__file__pb2.FileReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
