# Generated by Django 3.1.4 on 2021-01-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210123_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_answer',
            name='file_id',
            field=models.TextField(default=''),
        ),
    ]
